#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: ' Koffer | Artifact Rake Utility' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  tasks:

    ####### Purge Preexisting Artifacts 
    - name: '{{ ansible_name_module }} | file | Purge pre-existing bundles'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ dir_platform }}'
        - '{{ dir_platform }}/nginx/osp/images.json'
        - '{{ dir_bundle }}/koffer-bundle.osp-{{ version_osp }}.tar.xz'
        - '{{ dir_bundle }}/koffer-bundle.osp-{{ version_osp }}.tar.xz.sha256'
      when: clean_purge_artifacts == True

- import_playbook: tree.yml         # Create base directory tree
- import_playbook: images.yml       # Download OCP Infra Container Images
- import_playbook: bundle.yml       # Bundle artifacts for airgap pivot
